### ISSUE TITLE
[💡SUG] 项目是否支持leave-one-out data splitting？

### ISSUE THREAD

**Issue by WangYuhan-0520** [RUCAIBox/RecBole-CDR#75]
由于一些跨域推荐模型采用的leave-one-out data splitting策略，但是在Recbole-CDR项目中具体执行时，评估设置如下：
```
eval_args:
  split: { 'LS': 'valid_and_test' }  #leave-one-out data splitting
  group_by: user
  order: RO
  mode: uni999
```

报错：
`python3.7/site-packages/recbole/data/interaction.py",line367,in<dictcomp>
new_inter = {col: torch.cat ([inter[col) for inter in interactions]) for col in columns_set}
TypeError: expected Tensor as element 0 in argument 0, but got Interaction`
